version: '3.7'

services:
  db:
    image: mysql:8.0  
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    security_opt:
      - seccomp:unconfined
  back:
    build:
      context: ./back/
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./back:/myapp
      - bundle:/usr/local/bundle
    depends_on:
      - db
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db
      DB_USERNAME: root
      TZ: Asia/Tokyo
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - ./front:/usr/src/app
    ports:
      - "3000:3000"
volumes:
  db:
    driver: local
  bundle:
    driver: local