name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1                   
  ECR_REPOSITORY_BACK: quicook-back
  ECR_REPOSITORY_FRONT: quicook-front
  ECS_SERVICE_BACK: quicook-back      
  ECS_SERVICE_FRONT: quicook-front      
  ECS_CLUSTER: quicook                
  ECS_TASK_DEFINITION_BACK: back-task.json    
  ECS_TASK/DEFINITION_FRONT: front-task.json                           
  CONTAINER_NAME_BACK: quicook-back   
  CONTAINER_NAME_FRONT: quicook-front      
                                              

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Tree Check
        run: |
          docker -v

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a
      
      - name: Docker Build
        run: |
          docker-compose build

      - name: Bundle Install
        run: |
          docker-compose run back bundle install 

      - name: Yarn Add
        run: |
          docker-compose run front sh -c "cd app && yarn --cache-folder /usr/src/app/app/.yarn_cache add @emotion/react@^11.10.5 @emotion/styled@^11.10.5 @mui/icons-material@^5.11.0 @mui/material@^5.11.3 axios@^1.2.2 react-hook-form@^7.43.0 react-router-dom@5 sass@^1.57.1"
          docker-compose down

      - name: Cache File
        run: |
          docker-compose run --rm front sh -c "rm -rf /usr/src/app/app/node_modules/.cache"
          docker-compose run --rm front sh -c "mkdir -p /usr/src/app/app/node_modules/.cache"
          docker-compose run --rm front sh -c "chown -R node:node /usr/src/app/app/node_modules/.cache"
          docker volume prune
          sleep 30
          docker-compose up

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/v2y9n7g3
          docker tag quicook_back:latest public.ecr.aws/v2y9n7g3/quicook-back:latest
          docker push public.ecr.aws/v2y9n7g3/quicook-back:latest
          docker tag quicook_front:latest public.ecr.aws/v2y9n7g3/quicook-front:latest
          docker push public.ecr.aws/v2y9n7g3/quicook-front:latest

      - name: Fill in the new image ID in the Amazon ECS task definition back
        id: task-def-back
        uses: aws-actions/amazon-ecs-render-task-definition@c804dfbdd57f713b6c079302a4c01db7017a36fc
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION_BACK }}
          container-name: ${{ env.CONTAINER_NAME_BACK }}
          image: quicook-back:latest

      - name: Deploy Amazon ECS task definition back
        uses: aws-actions/amazon-ecs-deploy-task-definition@df9643053eda01f169e64a0e60233aacca83799a
        with:
          task-definition: ${{ steps.task-def-back.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE_BACK }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true

      - name: Fill in the new image ID in the Amazon ECS task definition front
        id: task-def-front
        uses: aws-actions/amazon-ecs-render-task-definition@c804dfbdd57f713b6c079302a4c01db7017a36fc
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION_FRONT }}
          container-name: ${{ env.CONTAINER_NAME_FRONT}}
          image: quicook-front:latest

      - name: Deploy Amazon ECS task definition front
        uses: aws-actions/amazon-ecs-deploy-task-definition@df9643053eda01f169e64a0e60233aacca83799a
        with:
          task-definition: ${{ steps.task-def-front.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE_FRONT }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
