name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1                   
  ECR_REPOSITORY_BACK: quicook-back
  ECR_REPOSITORY_FRONT: quicook-front
  ECS_SERVICE_BACK: quicook-back      
  ECS_SERVICE_FRONT: quicook-front      
  ECS_CLUSTER: quicook                
  ECS_TASK_DEFINITION_BACK: back-task.json    
  ECS_TASK/DEFINITION_FRONT: front-task.json                           
  CONTAINER_NAME_BACK: quicook-back   
  CONTAINER_NAME_FRONT: quicook-front      
                                              

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Tree Check
        run: |
          docker -v

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a
      
      - name: Wait for services to start
        run: |
          docker-compose build
          sleep 30

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker-compose build
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/v2y9n7g3
          docker tag quicook-back:latest public.ecr.aws/v2y9n7g3/quicook-back:latest
          docker push public.ecr.aws/v2y9n7g3/quicook-back:latest
          docker tag quicook-front:latest public.ecr.aws/v2y9n7g3/quicook-front:latest
          docker push public.ecr.aws/v2y9n7g3/quicook-front:latest

      - name: Fill in the new image ID in the Amazon ECS task definition back
        id: task-def-back
        uses: aws-actions/amazon-ecs-render-task-definition@c804dfbdd57f713b6c079302a4c01db7017a36fc
        with:
          task-definition-back: ${{ env.ECS_TASK_DEFINITION_BACK }}
          container-name: ${{ env.CONTAINER_NAME_BACK }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition back
        uses: aws-actions/amazon-ecs-deploy-task-definition@df9643053eda01f169e64a0e60233aacca83799a
        with:
          task-definition: ${{ steps.task-def-back.outputs.task-definition-back }}
          service: ${{ env.ECS_SERVICE_BACK }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true

      - name: Fill in the new image ID in the Amazon ECS task definition front
        id: task-def-front
        uses: aws-actions/amazon-ecs-render-task-definition@c804dfbdd57f713b6c079302a4c01db7017a36fc
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION_FRONT }}
          container-name: ${{ env.CONTAINER_NAME_FRONT}}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition front
        uses: aws-actions/amazon-ecs-deploy-task-definition@df9643053eda01f169e64a0e60233aacca83799a
        with:
          task-definition: ${{ steps.task-def-front.outputs.task-definition-front }}
          service: ${{ env.ECS_SERVICE_FRONT }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
