name: Stop

on:
  pull:
    branches:
      - main

jobs:
  stop:
    runs-on: ubuntu-latest 

    steps:
      - name: Ubuntu Check
        run: |    
          echo "これはシェルコマンドです"

      - name: Configure SSH
        env:
          PRIVATE_KEY: ${{ secrets.SECRET_KEY }}
        run: |
           echo "$PRIVATE_KEY" > key.pem
           chmod 400 key.pem
           ssh-keyscan -H 44.201.153.171 >> konwn_hosts

      - name: Ec2 to SSH
        run: |
           ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-44-201-153-171.compute-1.amazonaws.com \
           "cd Quicook_after && \
            docker-compose down"